### ISSUE TITLE
Add Boltdb driver

### ISSUE THREAD

**Issue by jcmartins** [manishrjain/gocrud#8]
See more: https://github.com/boltdb/bolt

tks
Joao

**Comment by manishrjain** [comment]
Sure. Want to send me a pull request? You can refer to how LevelDB is done:
https://github.com/manishrjain/gocrud/tree/master/drivers/leveldb

**Comment by manishrjain** [comment]
Drivers would no longer be created or maintained by Gocrud. See #18.
