### ISSUE TITLE
Cayley  - graphos database

### ISSUE THREAD

**Issue by jcmartins** [manishrjain/gocrud#9]
@manishrjain do you know [Cayley](https://github.com/google/cayley) ?

What you think about integrated Gocrud with Cayley?  Is it possible? If you have interest can I help you?

regards,
Joao

**Comment by manishrjain** [comment]
Sure. It would be great to get Cayley integrated.

**Comment by manishrjain** [comment]
Btw, also consider: http://www.cockroachlabs.com/

**Comment by manishrjain** [comment]
Drivers are going to be moved out of the main project. Creating / maintaining drivers would be left to volunteers and would be outside the scope of Gocrud project.
